In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import bqplot
from bqplot import market_map
import traitlets
import ipywidgets

In [2]:
dogs = pd.read_csv("/Users/erikaweir/Downloads/NYC_Dog_Licensing_Dataset.csv")
dogs

,RowNumber,AnimalName,AnimalGender,AnimalBirthMonth,BreedName,Borough,ZipCode,CommunityDistrict,CensusTract2010,NTA,CityCouncilDistrict,CongressionalDistrict,StateSenatorialDistrict,LicenseIssuedDate,LicenseExpiredDate
0,69143,SNICKERS,F,1/1/05 0:00,Dachshund Smooth Coat Miniature,Queens,11692.0,414.0,94203.0,QN12,32.0,5.0,15.0,4/29/16,3/29/17
1,4081,LEO,M,2/1/11 0:00,Bichon Frise,Queens,11106.0,401.0,47.0,QN70,26.0,12.0,12.0,1/26/15,2/22/16
2,32032,OLIVE,F,3/1/11 0:00,Unknown,Queens,11102.0,401.0,83.0,QN71,22.0,12.0,12.0,9/6/15,10/2/17
3,47466,LEO,M,2/1/11 0:00,Bichon Frise,Queens,11106.0,401.0,47.0,QN70,26.0,12.0,12.0,1/14/16,2/22/17
4,52611,ALASKA,F,5/1/15 0:00,American Eskimo dog,Queens,11102.0,401.0,125.0,QN72,22.0,14.0,12.0,2/12/16,2/12/17
5,76930,GIZMO,M,5/1/13 0:00,Chihuahua,Queens,11103.0,401.0,6502.0,QN70,22.0,12.0,12.0,6/1/16,1/26/17
6,58815,STARR,F,9/1/09 0:00,Chihuahua,Bronx,11231.0,306.0,75.0,BK33,39.0,7.0,26.0,3/15/16,2/25/17
7,108423,COCO,F,6/1/12 0:00,Jack Russell Terrier,Queens,11364.0,411.0,129104.0,QN42,23.0,6.0,11.0,10/13/16,11/27/17
8,63667,PATRON,M,5/1/11 0:00,Unknown,Queens,11694.0,414.0,928.0,QN10,32.0,5.0,15.0,4/6/16,2/9/17
9,100710,LOGAN,M,2/1/09 0:00,American Pit Bull Mix / Pit Bull Mix,Queens,11435.0,408.0,214.0,QN35,24.0,6.0,14.0,9/8/16,9/1/17
10,100711,LOGAN,M,2/1/09 0:00,American Pit Bull Mix / Pit Bull Mix,Queens,11435.0,408.0,214.0,QN35,24.0,6.0,14.0,9/8/16,9/1/18
11,57312,CJ,M,5/1/14 0:00,American Pit Bull Mix / Pit Bull Mix,Bronx,11422.0,413.0,664.0,QN05,31.0,5.0,10.0,3/7/16,3/7/17
12,14898,SUZZY,F,1/1/15 0:00,Unknown,Bronx,11356.0,407.0,919.0,QN23,19.0,14.0,11.0,4/27/15,4/27/16
13,47601,BUDDY,M,6/1/11 0:00,Unknown,Bronx,11379.0,405.0,659.0,QN21,30.0,6.0,15.0,1/14/16,2/16/17
14,49507,KIM,F,3/1/07 0:00,Rottweiler,Bronx,11206.0,301.0,503.0,BK90,34.0,7.0,18.0,1/27/16,12/27/16
15,107024,OREO,M,1/1/00 0:00,Shih Tzu,Bronx,11206.0,301.0,485.0,BK78,34.0,7.0,18.0,10/5/16,9/29/17
16,116665,BRUNO,M,11/1/13 0:00,American Pit Bull Mix / Pit Bull Mix,Bronx,11237.0,304.0,409.0,BK77,37.0,7.0,18.0,11/27/16,11/27/17
17,2126,FLIP,M,12/1/05 0:00,Shih Tzu,Bronx,11239.0,305.0,105801.0,BK93,42.0,8.0,19.0,1/3/15,1/3/16
18,8120,NAME NOT PROVIDED,M,10/1/14 0:00,Unknown,Bronx,11212.0,316.0,896.0,BK81,42.0,9.0,19.0,3/5/15,3/5/16
19,40685,NAME NOT PROVIDED,F,7/1/12 0:00,Yorkshire Terrier,Bronx,11236.0,316.0,922.0,BK81,42.0,8.0,19.0,11/23/15,10/26/16
20,59227,DIAMOND,F,1/1/12 0:00,Yorkshire Terrier,Bronx,11207.0,305.0,1078.0,BK82,42.0,8.0,19.0,3/16/16,3/16/17
21,5230,NAME NOT PROVIDED,F,9/1/14 0:00,Chihuahua,Bronx,11209.0,310.0,54.0,BK31,43.0,11.0,22.0,2/6/15,2/6/16
22,111241,UNKNOWN,M,7/1/16 0:00,Yorkshire Terrier Crossbreed,Bronx,10301.0,501.0,7.0,SI22,49.0,11.0,23.0,10/27/16,10/27/17
23,37585,SAMANTHA,F,1/1/04 0:00,Unknown,Bronx,10306.0,503.0,12805.0,SI25,50.0,11.0,24.0,10/26/15,10/30/16
24,109601,KYRA,F,1/1/05 0:00,Unknown,Bronx,10306.0,503.0,12805.0,SI25,50.0,11.0,24.0,10/19/16,11/29/17
25,105166,JACOB,M,1/1/06 0:00,Unknown,Bronx,11201.0,302.0,501.0,BK09,33.0,7.0,26.0,9/27/16,11/6/17
26,22006,ANGEL,M,11/1/03 0:00,Maltese,Bronx,10455.0,201.0,31.0,BX39,8.0,15.0,29.0,6/21/15,7/18/16
27,89373,ONYX,M,4/1/15 0:00,Maltese,Bronx,10454.0,201.0,23.0,BX39,8.0,15.0,29.0,7/20/16,7/20/18
28,116,SNOOPY,M,6/1/12 0:00,Unknown,Bronx,10454.0,201.0,2701.0,BX39,8.0,15.0,29.0,9/18/14,9/6/19
29,388,CYPHA,M,10/1/06 0:00,Unknown,Bronx,10452.0,204.0,195.0,BX63,8.0,15.0,29.0,10/11/14,3/17/17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121906,115617,TUFF,M,8/1/05 0:00,Pekingese,Staten Island,10309.0,NaN,NaN,NaN,NaN,NaN,NaN,11/18/16,1/31/17
121907,115663,SIMBA,M,10/1/13 0:00,American Pit Bull Mix / Pit Bull Mix,Staten Island,10312.0,NaN,NaN,NaN,NaN,NaN,NaN,11/19/16,11/19/17
121908,116016,ZEKE,M,6/1/10 0:00,Unknown,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,11/21/16,1/5/18
121909,116541,HARLEY,M,10/1/08 0:00,Maltese,Staten Island,10312.0,NaN,NaN,NaN,NaN,NaN,NaN,11/26/16,12/30/17
121910,117337,NIKKO,M,5/1/11 0:00,Chihuahua,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,12/2/16,12/3/17
121911,118026,AVA,F,1/1/08 0:00,"Schnauzer, Miniature",Staten Island,10306.0,NaN,NaN,NaN,NaN,NaN,NaN,12/6/16,12/29/17
121912,118875,METTRY,M,9/1/16 0:00,Shih Tzu,Staten Island,10312.0,NaN,NaN,NaN,NaN,NaN,NaN,12/9/16,12/9/17
121913,119826,GINO,M,1/1/08 0:00,German Shepherd Crossbreed,Staten Island,10307.0,NaN,NaN,NaN,NaN,NaN,NaN,12/15/16,1/14/18
121914,119874,LEMON,M,4/1/16 0:00,Siberian Husky,Staten Island,10308.0,NaN,NaN,NaN,NaN,NaN,NaN,12/15/16,12/15/17
121915,119974,OCHS,F,10/1/16 0:00,Shih Tzu,Staten Island,10304.0,NaN,NaN,NaN,NaN,NaN,NaN,12/16/16,12/16/17
121916,120110,SUIRIDOVSKY,M,10/1/16 0:00,Shih Tzu,Staten Island,10308.0,NaN,NaN,NaN,NaN,NaN,NaN,12/17/16,12/17/17
121917,120316,SASHA,F,4/1/15 0:00,Pomeranian Crossbreed,Staten Island,11967.0,NaN,NaN,NaN,NaN,NaN,NaN,12/19/16,12/19/17
121918,120397,THORBABY,M,9/1/07 0:00,German Shepherd Dog,Staten Island,10312.0,NaN,NaN,NaN,NaN,NaN,NaN,12/19/16,10/22/17
121919,120738,P.J.,F,8/1/09 0:00,Pug,Staten Island,10309.0,NaN,NaN,NaN,NaN,NaN,NaN,12/21/16,1/4/18
121920,121049,NAME,M,8/1/16 0:00,Beagle,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,12/24/16,12/24/17
121921,121314,BELLA,F,12/1/15 0:00,Chihuahua Crossbreed,Staten Island,10312.0,NaN,NaN,NaN,NaN,NaN,NaN,12/27/16,12/27/18
121922,121460,ROXIE,F,9/1/14 0:00,Maltese Crossbreed,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,12/28/16,1/5/18
121923,121464,ROCKY,M,3/1/13 0:00,Boxer,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,12/28/16,9/21/17
121924,121470,MORGAN,F,6/1/07 0:00,American Pit Bull Mix / Pit Bull Mix,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,12/28/16,2/18/18
121925,121478,KOBE,M,10/1/16 0:00,Shiba Inu,Staten Island,10312.0,NaN,NaN,NaN,NaN,NaN,NaN,12/28/16,12/28/17
121926,121550,APOLLO,M,8/1/16 0:00,American Pit Bull Mix / Pit Bull Mix,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,12/28/16,12/28/17
121927,121933,BAILEY,M,9/1/03 0:00,Yorkshire Terrier,Staten Island,10312.0,NaN,NaN,NaN,NaN,NaN,NaN,12/29/16,1/30/18
121928,122106,HENRY,M,1/1/04 0:00,Unknown,Staten Island,10312.0,NaN,NaN,NaN,NaN,NaN,NaN,12/30/16,12/30/17
121929,56268,BINKY,M,10/1/14 0:00,Yorkshire Terrier,Staten Island,10305.0,501.0,8.0,SI37,49.0,11.0,23.0,3/1/16,3/1/17
121930,17477,CHLOE,F,1/1/09 0:00,"Poodle, Toy",Manhattan,32163.0,NaN,NaN,NaN,NaN,NaN,NaN,5/15/15,6/12/17
121931,113760,CODY,M,3/1/09 0:00,German Shepherd Dog,Queens,11377.0,402.0,235.0,QN31,26.0,14.0,12.0,11/10/16,10/19/17
121932,116280,LAYLA,F,7/1/13 0:00,Unknown,Queens,11377.0,402.0,245.0,QN63,26.0,14.0,12.0,11/23/16,10/8/17
121933,58781,SNOOPY,M,4/1/14 0:00,Cocker Spaniel,Queens,11377.0,401.0,163.0,QN70,26.0,14.0,13.0,3/15/16,3/15/18
121934,61478,PRIMO,M,12/1/15 0:00,Poodle Crossbreed,Queens,11377.0,402.0,251.0,QN63,26.0,14.0,12.0,3/27/16,3/27/17
121935,51790,BLU \tM\t10/01/2015\t1\tMaltese\tBronx\t10473\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
topName = dogs["AnimalName"].value_counts()
topName

UNKNOWN              2467
NAME NOT PROVIDED    1764
BELLA                1008
MAX                  1001
CHARLIE               750
LOLA                  685
ROCKY                 668
COCO                  642
LUCY                  581
BUDDY                 559
LUCKY                 551
DAISY                 507
LUNA                  463
BAILEY                429
PRINCESS              428
CHLOE                 419
TEDDY                 417
TOBY                  415
MOLLY                 411
JACK                  351
BELLA                 351
MILO                  349
SOPHIE                341
PENNY                 334
OLIVER                334
COOPER                319
LILY                  314
COCO                  301
STELLA                299
LEO                   293
                     ...
FLAKE                   1
BONNIEBELLE             1
KEEPER                  1
BOOEY                   1
EMORY                   1
GILLIE                  1
JIZZLE                  1
KYNA                    1
NESTA                   1
ASTIN                   1
TASSIE                  1
LUK                     1
SHAGGY'S                1
KOKIE                   1
BEO                     1
ROMEY                   1
ZAICHIK                 1
LOENGRIN                1
BABS                    1
GOD'S                   1
KATERINA                1
CHO-CO                  1
BRUNO-VAZQUEZ           1
SKELLY                  1
PORC                    1
BUCKINGTON              1
LUNA-PEARL              1
KERWYN                  1
TEN                     1
AYALA                   1
Name: AnimalName, Length: 20735, dtype: int64

In [4]:
# https://stackoverflow.com/questions/30405413/python-pandas-extract-year-from-datetime-dfyear-dfdate-year-is-not/33757291
dogs["AnimalBirthMonth"] = pd.to_datetime(dogs["AnimalBirthMonth"])
dogs["year"] = dogs["AnimalBirthMonth"].dt.year
#df = f.sort_values("AnimalBirthMonth")

nm = ["BELLA", "MAX", "CHARLIE", "LOLA", "ROCKY", "COCO", "LUCY", "BUDDY", "LUCKY", "DAISY"]
df = dogs.loc[(dogs["AnimalName"].isin(nm))]
#if any(i in f["AnimalName"] for i in nm):
#    df = f.loc[f["AnimalName"] == i]
df

,RowNumber,AnimalName,AnimalGender,AnimalBirthMonth,BreedName,Borough,ZipCode,CommunityDistrict,CensusTract2010,NTA,CityCouncilDistrict,CongressionalDistrict,StateSenatorialDistrict,LicenseIssuedDate,LicenseExpiredDate,year
7,108423,COCO,F,2012-06-01,Jack Russell Terrier,Queens,11364.0,411.0,129104.0,QN42,23.0,6.0,11.0,10/13/16,11/27/17,2012.0
13,47601,BUDDY,M,2011-06-01,Unknown,Bronx,11379.0,405.0,659.0,QN21,30.0,6.0,15.0,1/14/16,2/16/17,2011.0
45,2825,COCO,F,2010-07-01,Unknown,Bronx,10454.0,201.0,41.0,BX39,8.0,15.0,29.0,1/13/15,1/13/16,2010.0
46,2826,COCO,F,2014-04-01,American Pit Bull Terrier/Pit Bull,Bronx,10454.0,201.0,39.0,BX39,8.0,15.0,29.0,1/13/15,1/13/16,2014.0
51,2965,BUDDY,M,2014-10-01,Unknown,Bronx,10454.0,201.0,39.0,BX39,8.0,15.0,29.0,1/14/15,1/14/16,2014.0
61,4123,MAX,M,2014-11-01,Australian Shepherd,Bronx,10454.0,201.0,39.0,BX39,8.0,15.0,29.0,1/27/15,1/27/16,2014.0
62,4476,ROCKY,M,2009-01-01,Beagle Crossbreed,Bronx,10451.0,204.0,63.0,BX63,8.0,15.0,29.0,1/30/15,1/30/16,2009.0
86,6669,LOLA,F,2012-11-01,Yorkshire Terrier,Bronx,10452.0,204.0,22102.0,BX63,16.0,15.0,29.0,2/21/15,2/25/16,2012.0
138,11382,MAX,M,2014-02-01,Staffordshire Bull Terrier,Bronx,10454.0,201.0,33.0,BX39,8.0,15.0,29.0,4/3/15,4/3/16,2014.0
155,12433,ROCKY,M,2012-06-01,Puggle,Bronx,10452.0,204.0,189.0,BX26,8.0,15.0,29.0,4/11/15,4/11/16,2012.0
158,12559,MAX,M,2003-11-01,Cocker Spaniel,Bronx,10454.0,201.0,41.0,BX39,8.0,15.0,29.0,4/12/15,5/14/17,2003.0
161,12846,MAX,M,2015-01-01,Yorkshire Terrier,Bronx,10452.0,204.0,197.0,BX63,16.0,15.0,29.0,4/14/15,4/14/16,2015.0
173,13797,COCO,F,2013-04-01,Shih Tzu,Bronx,10452.0,204.0,195.0,BX63,16.0,15.0,29.0,4/21/15,4/21/16,2013.0
242,19735,COCO,F,2003-01-01,Pug,Bronx,10453.0,205.0,21502.0,BX36,14.0,15.0,29.0,6/3/15,6/3/16,2003.0
244,19798,BELLA,F,2014-01-01,Pomeranian,Bronx,10453.0,205.0,243.0,BX36,14.0,15.0,29.0,6/4/15,6/4/20,2014.0
248,19957,ROCKY,M,2015-04-01,Labrador Retriever,Bronx,10452.0,204.0,22102.0,BX63,16.0,15.0,29.0,6/5/15,6/5/16,2015.0
264,20849,BELLA,F,2006-05-01,Dachshund Smooth Coat,Bronx,10451.0,201.0,51.0,BX39,8.0,15.0,29.0,6/12/15,6/30/16,2006.0
266,21000,LOLA,F,2014-09-01,Shih Tzu,Bronx,10454.0,201.0,2701.0,BX39,8.0,15.0,29.0,6/12/15,6/12/16,2014.0
277,21758,LOLA,F,2012-01-01,Pomeranian,Bronx,10453.0,205.0,21502.0,BX36,14.0,15.0,29.0,6/18/15,6/18/16,2012.0
289,23005,BELLA,F,2010-08-01,"Poodle, Miniature",Bronx,10452.0,204.0,189.0,BX26,8.0,15.0,29.0,6/27/15,6/27/16,2010.0
311,25551,COCO,F,2015-05-01,Yorkshire Terrier Crossbreed,Bronx,10453.0,205.0,20501.0,BX36,14.0,15.0,29.0,7/18/15,7/18/16,2015.0
312,25567,ROCKY,M,2012-10-01,Bull Terrier,Bronx,10455.0,201.0,79.0,BX34,8.0,15.0,29.0,7/18/15,7/18/16,2012.0
379,32175,CHARLIE,M,2005-01-01,Unknown,Bronx,10455.0,201.0,35.0,BX39,8.0,15.0,29.0,9/8/15,9/21/16,2005.0
381,32389,MAX,M,2015-05-01,Jack Russell Terrier,Bronx,10454.0,201.0,39.0,BX39,8.0,15.0,29.0,9/9/15,9/9/16,2015.0
406,34162,LUCKY,M,2012-03-01,Yorkshire Terrier,Bronx,10455.0,201.0,79.0,BX34,17.0,15.0,29.0,9/25/15,9/25/16,2012.0
407,34400,COCO,F,2013-05-01,American Pit Bull Terrier/Pit Bull,Bronx,10454.0,201.0,2702.0,BX39,8.0,15.0,29.0,9/28/15,9/28/16,2013.0
446,38068,LUCKY,M,2004-01-01,Chihuahua,Bronx,10455.0,201.0,79.0,BX34,17.0,15.0,29.0,10/30/15,3/12/16,2004.0
466,39383,MAX,M,2014-02-01,Unknown,Bronx,10454.0,201.0,2701.0,BX39,8.0,15.0,29.0,11/12/15,11/3/16,2014.0
474,40176,MAX,M,2006-05-01,Lhasa Apso,Bronx,10455.0,201.0,79.0,BX34,17.0,15.0,29.0,11/18/15,11/4/17,2006.0
504,42522,LUCKY,M,2009-07-01,Chihuahua,Bronx,10455.0,201.0,43.0,BX39,8.0,15.0,29.0,12/8/15,12/4/16,2009.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121621,2323,BUDDY,M,2009-08-01,Pug,Staten Island,10309.0,NaN,NaN,NaN,NaN,NaN,NaN,1/6/15,1/4/16,2009.0
121647,14095,LUCY,F,2009-04-01,Boxer,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,4/22/15,4/12/16,2009.0
121673,22773,MAX,M,2008-01-01,Golden Retriever,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,6/26/15,6/30/16,2008.0
121674,22802,COCO,F,2010-02-01,Shih Tzu,Staten Island,10309.0,NaN,NaN,NaN,NaN,NaN,NaN,6/26/15,7/27/16,2010.0
121688,30111,BUDDY,M,2011-01-01,Unknown,Staten Island,10307.0,NaN,NaN,NaN,NaN,NaN,NaN,8/20/15,8/22/16,2011.0
121700,35321,BUDDY,M,2015-04-01,Ibizan Hound,Staten Island,10306.0,NaN,NaN,NaN,NaN,NaN,NaN,10/7/15,10/7/16,2015.0
121705,36166,BELLA,F,2002-01-01,Yorkshire Terrier,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,10/15/15,10/26/16,2002.0
121706,36526,MAX,M,2011-02-01,American Pit Bull Terrier/Pit Bull,Staten Island,10305.0,NaN,NaN,NaN,NaN,NaN,NaN,10/17/15,10/15/16,2011.0
121712,37842,LUCKY,M,2005-01-01,Doberman Pinscher,Staten Island,10306.0,NaN,NaN,NaN,NaN,NaN,NaN,10/28/15,10/1/16,2005.0
121747,49603,COCO,F,2012-04-01,"Poodle, Miniature",Staten Island,10305.0,NaN,NaN,NaN,NaN,NaN,NaN,1/27/16,12/17/16,2012.0
121754,50766,COCO,F,2005-12-01,Unknown,Staten Island,10308.0,NaN,NaN,NaN,NaN,NaN,NaN,2/2/16,3/11/17,2005.0
121758,52734,COCO,F,2010-02-01,Shih Tzu,Staten Island,10308.0,NaN,NaN,NaN,NaN,NaN,NaN,2/12/16,3/2/17,2010.0
121767,56619,MAX,M,2015-09-01,Rottweiler,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,3/3/16,3/3/17,2015.0
121775,61010,LUCY,F,2009-04-01,Boxer,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,3/24/16,4/12/17,2009.0
121780,62726,BUDDY,M,2006-08-01,West High White Terrier,Staten Island,10308.0,NaN,NaN,NaN,NaN,NaN,NaN,4/1/16,4/29/17,2006.0
121788,64317,BELLA,F,2006-01-01,Shih Tzu,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,4/8/16,5/13/17,2006.0
121792,66959,BUDDY,M,2013-02-01,Unknown,Staten Island,10306.0,NaN,NaN,NaN,NaN,NaN,NaN,4/20/16,5/23/17,2013.0
121795,68541,CHARLIE,M,2016-01-01,Pomeranian,Staten Island,10308.0,NaN,NaN,NaN,NaN,NaN,NaN,4/26/16,4/26/17,2016.0
121801,72570,COCO,F,2010-08-01,Chihuahua,Staten Island,10305.0,NaN,NaN,NaN,NaN,NaN,NaN,5/13/16,7/2/17,2010.0
121820,79959,CHARLIE,M,2002-02-01,Beagle Crossbreed,Staten Island,28677.0,NaN,NaN,NaN,NaN,NaN,NaN,6/13/16,5/29/17,2002.0
121825,82619,MAX,M,2004-01-01,West High White Terrier,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,6/24/16,7/30/17,2004.0
121833,84599,DAISY,F,2009-10-01,Labrador Retriever Crossbreed,Staten Island,10312.0,NaN,NaN,NaN,NaN,NaN,NaN,7/1/16,8/7/17,2009.0
121853,92430,BELLA,F,2016-05-01,Coton de Tulear,Staten Island,11024.0,NaN,NaN,NaN,NaN,NaN,NaN,8/3/16,8/3/17,2016.0
121860,94794,BUDDY,M,2011-01-01,Unknown,Staten Island,10307.0,NaN,NaN,NaN,NaN,NaN,NaN,8/11/16,8/22/17,2011.0
121872,100312,BUDDY,M,2007-11-01,"Coonhound, Treeing Walker",Staten Island,10306.0,NaN,NaN,NaN,NaN,NaN,NaN,9/7/16,9/14/17,2007.0
121883,105381,LUCKY,M,2012-03-01,American Pit Bull Terrier/Pit Bull,Staten Island,11731.0,NaN,NaN,NaN,NaN,NaN,NaN,9/28/16,9/28/17,2012.0
121884,105698,BELLA,F,2002-01-01,Yorkshire Terrier,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,9/29/16,10/26/17,2002.0
121890,107375,LUCKY,F,2011-05-01,"Poodle, Miniature",Staten Island,10305.0,NaN,NaN,NaN,NaN,NaN,NaN,10/7/16,10/18/17,2011.0
121897,110915,ROCKY,M,2004-01-01,Yorkshire Terrier,Staten Island,10306.0,NaN,NaN,NaN,NaN,NaN,NaN,10/24/16,11/30/17,2004.0
121923,121464,ROCKY,M,2013-03-01,Boxer,Staten Island,10314.0,NaN,NaN,NaN,NaN,NaN,NaN,12/28/16,9/21/17,2013.0

In [5]:
#date = f["LicenseIssuedDate"].tolist()
#year = []
#for i in date:
#    year.append(date[i][-2:])

#year

#bd = f.loc[f["AnimalName"] == "BELLA"]["year"].value_counts().sort_values().tolist()
#bd
#nmByYr = []

nm = ["BELLA", "MAX", "CHARLIE", "LOLA", "ROCKY", "COCO", "LUCY", "BUDDY", "LUCKY", "DAISY"]
#for i in range(len(names)):
#    bd = f.loc[f["AnimalName"] == nm[i]]["year"].value_counts().sort_values()#.tolist()
#    nmByYr.append(bd)

#print(nmByYr)
dogN = df.groupby("AnimalName")["RowNumber"].count()
dogN = dogN.sort_values(ascending = False)
dogN

AnimalName
BELLA      1008
MAX        1001
CHARLIE     750
LOLA        685
ROCKY       668
COCO        642
LUCY        581
BUDDY       559
LUCKY       551
DAISY       507
Name: RowNumber, dtype: int64

In [8]:
# n = np.arange(10)
# names = ["Bella", "Max", "Charlie", "Lola", "Rocky", "Coco", "Lucy", "Buddy", "Lucky", "Daisy"]
# plt.bar(n, topName[2:12])
# plt.xticks(n, names)

In [23]:
#names = ["Bella", "Max", "Charlie", "Lola", "Rocky", "Coco", "Lucy", "Buddy", "Lucky", "Daisy"]
#xr = np.arange(10)

#x_br = bqplot.LinearScale()
#y_br = bqplot.LinearScale()
#xa_br = bqplot.Axis(scale = x_br, label = "Name")#, tick_format = 'string', tick_values = names)
#ya_br = bqplot.Axis(scale = y_br, label = "Counts", orientation = 'vertical')

#bars = bqplot.Bars(x = xr, y = dogN.values, scales = {'x': x_br, 'y': y_br}, colors = ['#B9D0F2'],
                  # interactions = {'click': 'select'}, selected_style = {'stroke': '#99CCFF', 'fill': '#F0F2B9'})
#fig1 = bqplot.Figure(title = "Top 10 Dog Names", axes = [xa_br, ya_br], marks = [bars])
#display(fig1)

In [30]:
#x_sc2 = bqplot.LinearScale(min = 1998, max = 2017)
#y_sc2 = bqplot.LinearScale()
#xa2 = bqplot.Axis(scale = x_sc2, label = "Year")
#ya2 = bqplot.Axis(scale = y_sc2, label = "Total counts", orientation = 'vertical')

#i = "BELLA"
#sel = (df["AnimalName"] == i)
#aa = df[sel]
#aa = aa.groupby("year")["RowNumber"].count()
#zz = np.arange(len(xx) + 1)

#right = bqplot.Lines(x = aa.index, y = aa.values, scales = {'x': x_sc2, 'y': y_sc2}, colors = ['#99CCFF'])
#fig2 = bqplot.Figure(title = "by Year", axes = [xa2, ya2], marks = [right])
#myLabel = ipywidgets.Label()

#def showYear(change):
 #   i = change['owner'].selected[0]
 #   v = dogN[i]
 #   myLabel.value = "Total count = " + str(v)
 #   sel = (df["AnimalName"] == i)
 #   aa = df[sel]
  #  aa = aa.groupby("year")["RowNumber"].count()
  #  right.x = aa.index
   # right.y = aa.values
    
#bars.observe(showYear, 'selected')    
#ipywidgets.VBox([myLabel, ipywidgets.HBox([fig1, fig2])])
#ipywidgets.VBox([myLabel, ipywidgets.HBox([mmap, fig2])])

In [6]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.OrdinalScale()
c_sc = bqplot.ColorScale(scheme = "BuPu")
xa = bqplot.Axis(scale = x_sc)
ya = bqplot.Axis(scale = y_sc, orientation = 'vertical')
ca = bqplot.ColorAxis(scale = c_sc, orientation = 'vertical', side = 'right')

mmap = bqplot.market_map.MarketMap(color = dogN.values, names = dogN.index.values,
                                   scales = {'color': c_sc}, axes = [ca])

myLabel = ipywidgets.Label()

def get_label(change):
    i = change['new'][-1:][0]
    v = dogN[i]
    myLabel.value = "Total count = " + str(v)
    
mmap.observe(get_label, 'selected')

ipywidgets.VBox([myLabel, ipywidgets.HBox([mmap])])

VBox(children=(Label(value=''), HBox(children=(MarketMap(axes=[ColorAxis(orientation='vertical', scale=ColorSc…

In [7]:
i = "BELLA"
sel = (df["AnimalName"] == i)
aa = df[sel]
aa = aa.groupby("year")["RowNumber"].count()
aa

year
2000.0      1
2001.0      4
2002.0      9
2003.0      9
2004.0     16
2005.0     34
2006.0     27
2007.0     67
2008.0     78
2009.0     77
2010.0    113
2011.0     96
2012.0     89
2013.0    105
2014.0    126
2015.0     92
2016.0     65
Name: RowNumber, dtype: int64

In [8]:
x_sc2 = bqplot.LinearScale(min = 1998, max = 2017)
y_sc2 = bqplot.LinearScale()
xa2 = bqplot.Axis(scale = x_sc2, label = "Year")
ya2 = bqplot.Axis(scale = y_sc2, label = "Total counts", orientation = 'vertical')

i = "BELLA"
sel = (df["AnimalName"] == i)
aa = df[sel]
aa = aa.groupby("year")["RowNumber"].count()

right = bqplot.Lines(x = aa.index, y = aa.values, scales = {'x': x_sc2, 'y': y_sc2}, colors = ['#B9D0F2'])
fig2 = bqplot.Figure(title = "by Year", axes = [xa2, ya2], marks = [right])


myLabel = ipywidgets.Label()

def get_label(change):
    i = change['new'][-1:][0]
    v = dogN[i]
    myLabel.value = "Total count = " + str(v)
    
mmap.observe(get_label, 'selected')

def showYear(change):
    i = change['new'][-1:][0]
    sel = (df["AnimalName"] == i)
    aa = df[sel]
    aa = aa.groupby("year")["RowNumber"].count()
    #bb = aa.values
    #cc = aa.index
    right.x = aa.index
    right.y = aa.values
    #print(change)
    
mmap.observe(showYear, 'selected')    
ipywidgets.VBox([myLabel, ipywidgets.HBox([mmap, fig2])])

VBox(children=(Label(value=''), HBox(children=(MarketMap(axes=[ColorAxis(orientation='vertical', scale=ColorSc…

In [34]:
#dogN

In [35]:
#dogN.values

In [36]:
#dogN.index.values